
---
- name: mysqld install
  #  hosts: DB 
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install MYSQL
      yum:
        name: mariadb-server #debian: mysql-server
        state: present

    - name: Install the Python MySQL Support Libraries
      yum: pkg=MySQL-python state=latest

    - name: start mysql server and enable it on reboot
      service: name=mariadb state=started enabled=true #debian: mysql


